image: java:8-jdk
stages:
  - test
  - build
services:
  - 'mongo:3.4-jessie'
variables:
  MONGO_DATABASENAME: muzixdb
  MONGO_URL: mongodb://mongo/muzixdb
cache:
  paths:
   - .m2/repository
   - target
maven-test:
  image: maven:3-jdk-8
  stage: test
<<<<<<< HEAD
  script: "mvn test -B"
=======
  script: "mvn test-B"
>>>>>>> 9a03a88d241969d0ce6f2aa3bfeab5784e99ad95
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -U"
  artifacts:
    paths:
      - target/*.jar

