version: '3'
services:
  Spring:
    image: ragour0001/muzixservicebackend:v1
    restart: always
    network_mode: host
    container_name: spring-image
    depends_on:
      - mongo
    ports:
      - 8084:8084

  angular:
    image: ragour0001/muzixservicefrontend:v1
    network_mode: host
    container_name: angular-docker
    ports:
      - 8080:8080

  mongo:
   image: mongo:3.2-jessie
   ports:
     - "27017:27017"
   container_name: mongo
   network_mode: host

