version: '3'
services:
  authService:
    image: ragour0001/authservicev2:v2
    restart: always
    network_mode: host
    depends_on:
      - mysql
      - eurekaServer
    ports:
      - 8085:8085

  userTrackService:
    image: ragour0001/usertackservicev2:v1
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - eurekaServer
    ports:
      - 8086:8086

  eurekaServer:
    image: ragour0001/eurekaservice:v1
    restart: always
    network_mode: host
    ports:
      - 9003:9003

  zuulService:
    image: ragour0001/zuulservice:v1
    restart: always
    network_mode: host
    ports:
      - 8087:8087 

  orchestrationService:
    image: ragour0001/orchestrationservice:v1
    restart: always
    network_mode: host
    depends_on:
      - eurekaServer
    ports:
      - 8888:8888

  mysql:
    image: mysql:5.5
    ports:
     - 3306:3306
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: UserDb
      MYSQL_USER: approot
      MYSQL_PASSWORD: root123
  
  angular:
    image: ragour0001/angularregister:v2
    network_mode: host
    container_name: angular-docker
    ports:
      - 8080:8080

  mongo:
    image: mongo:3.2-jessie
    ports:
     - 27017:27017
    container_name: mongo
    network_mode: host

